print('Helo \t World')
print("Helo \n World")
print(92)
# print("This is 'Abdullah Asif' here")
# print('This is "Abdullah Asif" here')
print('This is \'Abdullah Asif\' here')
print("This is \"Abdullah Asif\" here")
print("This is backslash \\")
print("Line A \\n Line B")